### ISSUE TITLE
Feedbacks import problem #2 

### ISSUE THREAD

**Issue by VictoriaSaden** [gorse-io/gorse#521] opened 2022-08-09 09:05 UTC
**Gorse version**
last version 

Hi, I still have the same issue, even if I put auto_insert_item = true in the configuration, feedbacks cannot be imported. Can you help me please ? 

**Describe the bug**
I imported my feedbacks in the Import feedbacks window on Gorse. However, in the Gorse Dashboard Overview I do not have any feedback displayed. Moreover, then, I exported the feedbacks from Gorse and there is literally nothing in there. It is as if Gorse fakes to import the feedbacks, but in reality it does not. I don't think it's a TimeStamp Type issue (but maybe it is), as I tried with many different types and it still doesn't work.

Even when I try with a csv file of 5 lines like this one it does not work :
favori,UserId,ItemId,Timestamp
favori,3423,186758,2022-06-24 21:20:11
favori,3423,186758,2022-06-24 21:20:13
favori,2823,186085,2022-06-24 21:20:19
favori,2140,185965,2022-06-24 21:20:20

**Comment by zhenghaoz** [comment] 2022-08-09 11:30
Duplicate of #517

**Closed by zhenghaoz** 2022-08-09 11:30 UTC
Labels: bug
